# Generated by Django 4.1 on 2022-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWatchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField()),
                ("title", models.CharField(max_length=255)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Bad"),
                            (2, "Not Good"),
                            (3, "Ok"),
                            (4, "Good"),
                            (5, "Great"),
                        ]
                    ),
                ),
                ("release_date", models.DateField()),
                ("review", models.TextField()),
            ],
        ),
    ]
