# Generated by Django 4.1 on 2022-09-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywatchlist",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MaxValueValidator(5.0),
                    django.core.validators.MinValueValidator(0.0),
                ]
            ),
        ),
    ]
